USE QuanLyGiaoVu;
--Chương 1 trang 11
--Bai 11
ALTER TABLE HOCVIEN
ADD CONSTRAINT CHK_TUOI
CHECK (YEAR(GETDATE())-YEAR(NGSINH) >= 18);
--Bai 12
ALTER TABLE GIANGDAY
ADD CONSTRAINT CHK_NGAYBATDAU
CHECK (TUNGAY < DENNGAY);

--Bai 13
ALTER TABLE GIAOVIEN
ADD CONSTRAINT CHK_TUOIGV
CHECK (YEAR(GETDATE())-YEAR(NGSINH)>=22);

--Bai 14
SELECT MAMH, TCLT, TCTH, ABS(TCLT - TCTH) AS Credit_Difference
FROM MONHOC
WHERE ABS(TCLT - TCTH) <= 3;

SELECT * FROM MONHOC;
--Chương 3 trang 12
-- bài 1
SELECT MAHV, HO, TEN , NGSINH, L.MALOP
FROM HOCVIEN HV 
JOIN LOP L 
ON HV.MAHV = L.TRGLOP;
-- Bai 2
SELECT HV.MAHV, HO, TEN, LANTHI, DIEM
FROM
    HOCVIEN HV JOIN KETQUATHI K ON HV.MAHV = K.MAHV
    JOIN LOP L ON HV.MALOP = L.MALOP
WHERE L.MALOP = 'K12'
AND K.MAMH='CTRR'
ORDER BY TEN ASC, HO ASC;
--Bai 3
SELECT HV.MAHV, HO, TEN
FROM
    HOCVIEN HV JOIN KETQUATHI K on HV.MAHV = K.MAHV
    JOIN MONHOC M on K.MAMH = M.MAMH
WHERE K.LANTHI = 1 AND K.KQUA = 'DAT';


--Bai 4

SELECT  HV.MAHV, HO, TEN
FROM
    HOCVIEN HV JOIN KETQUATHI K on HV.MAHV = K.MAHV
WHERE HV.MALOP ='K11' AND K.LANTHI = '1' AND K.KQUA='Khong dat' AND K.MAMH ='CTRR'

--Bai 5

SELECT DISTINCT
    H.MAHV,HO,TEN
FROM
    KETQUATHI K1 JOIN HOCVIEN H on K1.MAHV = H.MAHV
WHERE
    H.MALOP LIKE 'K%' AND MAMH='CTRR' AND  NOT EXISTS(
            SELECT * FROM KETQUATHI K2
            WHERE KQUA='DAT' AND MAMH='CTRR' AND K1.MAHV=K2.MAHV
            )
