USE QuanLyBanHang;
--Chương 2 trang 4
--Bài 2
CREATE TABLE KHACHHANG1
(
    MAKH    VARCHAR(4) PRIMARY KEY,
    HOTEN   VARCHAR(40),
    DCHI    VARCHAR(50),
    SODT    VARCHAR(20),
    NGSINH  SMALLDATETIME,
	NGDK    SMALLDATETIME,
    DOANHSO MONEY,
	LOAIKH VARCHAR(20),
);
CREATE TABLE SANPHAM1
(
    MASP   VARCHAR(4) PRIMARY KEY,
    TENSP  VARCHAR(40),
    DVT    VARCHAR(20),
    NUOCSX VARCHAR(40),
    GIA    MONEY,
);
INSERT INTO SANPHAM1
SELECT *
FROM SANPHAM;

INSERT INTO KHACHHANG1
SELECT *
FROM KHACHHANG;

--Bai 3
UPDATE SANPHAM1
SET GIA =GIA + GIA * 0.05
WHERE NUOCSX = 'Thai Lan';

--Bai 4
UPDATE SANPHAM1
SET GIA =GIA - GIA * 0.05
WHERE NUOCSX = 'Trung Quoc'
  AND GIA <= 10000;

--Bai 5
SELECT *
FROM KHACHHANG1

UPDATE KHACHHANG1
SET LOAIKH = 'Vip'
WHERE (NGDK < '2007-1-1' AND DOANHSO >= 10000000)
   OR (NGDK >= '2007-1-1' AND DOANHSO >= 2000000);
SELECT *
FROM KHACHHANG1;

--chương 3 trang 4
--bài 1
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'TRUNG QUOC';
--Bai 2
SELECT MASP, TENSP
FROM SANPHAM
WHERE DVT IN ('CAY', 'QUYEN');
--Bai 3
SELECT MASP, TENSP
FROM SANPHAM
WHERE MASP LIKE ('B%01');
--Bai 4
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX = 'TRUNG QUOC'
  AND (GIA BETWEEN 30000 AND 40000);
--Bai 5
SELECT MASP, TENSP
FROM SANPHAM
WHERE NUOCSX IN ('TRUNG QUOC', 'THAI LAN')
  AND (GIA BETWEEN 30000 AND 40000);
--Bai 6
SELECT SOHD, TRIGIA
FROM HOADON
WHERE NGHD IN ('2007-1-1', '2007-1-2');
--Bai 7
SELECT SOHD, TRIGIA
FROM HOADON
WHERE YEAR(NGHD) = '2007'
  AND MONTH(NGHD) = 1
ORDER BY NGHD ASC, TRIGIA DESC;
--Bai 8
SELECT DISTINCT K.MAKH, K.HOTEN 
FROM KHACHHANG K
         INNER JOIN
     HOADON H ON K.MAKH = H.MAKH
WHERE NGHD = '2007-01-01';
--Bai 9
SELECT SOHD, TRIGIA
FROM HOADON H
         INNER JOIN
     NHANVIEN N ON H.MANV = N.MANV
WHERE HOTEN = 'Nguyen Van B'
  AND NGHD = '2006-10-28';
--Bai 10
SELECT S.MASP, TENSP
FROM SANPHAM S
         INNER JOIN
     (
         (SELECT SOHD
          FROM HOADON H
                   JOIN
               KHACHHANG K on H.MAKH = K.MAKH
          WHERE HOTEN = 'Nguyen Van A'
            AND YEAR(NGHD) = '2006'
            AND MONTH(NGHD) = '10') AS HDKH
             INNER JOIN
             CTHD ON CTHD.SOHD = HDKH.SOHD
         ) ON S.MASP = CTHD.MASP

--Bai 11
SELECT DISTINCT SOHD
FROM CTHD
WHERE MASP IN ('BB01', 'BB02');
