--PHAN II QUANLYGIAOVU
USE QuanLyGiaoVu;
-- ALTER TABLE HOCVIEN
ALTER TABLE HOCVIEN
ADD GHICHU VARCHAR(100);

ALTER TABLE HOCVIEN
ADD DIEMTB NUMERIC(4,2);

ALTER TABLE HOCVIEN
ADD XEPLOAI VARCHAR(10);
--Bai 1
UPDATE GIAOVIEN
SET	HESO = HESO + 0.2
WHERE MAGV IN (SELECT TRGKHOA FROM KHOA)

--Bai 2
UPDATE HOCVIEN
SET DIEMTB = (
        SELECT AVG(DIEM)
        FROM KETQUATHI KQ1
        WHERE LANTHI = (SELECT MAX(LANTHI) FROM KETQUATHI KQ2 WHERE KQ1.MAHV = KQ2.MAHV  GROUP BY KQ2.MAHV) AND HOCVIEN.MAHV = KQ1.MAHV
        GROUP BY KQ1.MAHV
    )
--Bai 3

UPDATE HOCVIEN
SET GHICHU = 'Cam thi'
WHERE EXISTS(SELECT *
				FROM KETQUATHI KQ
				WHERE (HOCVIEN.MAHV = KQ.MAHV) AND (KQ.DIEM < 5) AND (LANTHI = 3))

--Bai 4
UPDATE HOCVIEN
SET XEPLOAI =
(
	CASE
		WHEN DIEMTB >=9 THEN 'XS'
		WHEN DIEMTB >= 8 AND DIEMTB < 9 THEN 'G'
		WHEN DIEMTB >= 6.5 AND DIEMTB < 8 THEN 'K'
		WHEN DIEMTB >= 5 AND DIEMTB < 6.5 THEN 'TB'
		WHEN DIEMTB < 5 THEN 'Y'
	END
)
-- Phan III QUANLYGIAOVU
--Bai 6
--C1
SELECT DISTINCT M.TENMH
FROM
    GIAOVIEN GV INNER JOIN GIANGDAY G on GV.MAGV = G.MAGV
    INNER JOIN MONHOC M on G.MAMH = M.MAMH
    WHERE GV.HOTEN = 'TRAN TAM THANH' AND G.HOCKY =1 AND G.NAM = 2006
--C2
SELECT DISTINCT TENMH FROM MONHOC
WHERE MAMH IN (SELECT MAMH FROM GIANGDAY 
			   WHERE HOCKY=1 
					AND NAM=2006 
					AND MAGV IN (SELECT MAGV FROM GIAOVIEN
								 WHERE HOTEN='TRAN TAM THANH')
			   )
--Bai 7
--C1
SELECT M.MAMH,TENMH
FROM
    LOP L INNER JOIN GIAOVIEN GV ON L.MAGVCN = GV.MAGV
    INNER JOIN GIANGDAY GD on GV.MAGV = GD.MAGV
    INNER JOIN MONHOC M on GD.MAMH = M.MAMH
WHERE L.MALOP ='K11' AND HOCKY=1 AND NAM=2006
--C2
SELECT MAMH, TENMH FROM MONHOC
WHERE MAMH IN (SELECT MAMH FROM GIANGDAY
			   WHERE HOCKY=1 
	           AND NAM=2006 
	           AND MAGV IN (SELECT MAGVCN FROM LOP 
						    WHERE MALOP='K11')
               )

--Bai 8
--C1
SELECT H.HO,H.TEN
    FROM
        GIAOVIEN GV INNER JOIN GIANGDAY GD on GV.MAGV = GD.MAGV
        INNER JOIN MONHOC M on GD.MAMH = M.MAMH
        INNER JOIN LOP L on GD.MALOP = L.MALOP
        INNER JOIN HOCVIEN H ON H.MAHV = L.TRGLOP
    WHERE HOTEN='NGUYEN TO LAN' AND TENMH='CO SO DU LIEU'
--C2
SELECT HO, TEN FROM HOCVIEN
WHERE MAHV IN (SELECT TRGLOP FROM LOP
	           WHERE MALOP IN (SELECT MALOP FROM GIANGDAY
			                   WHERE MAGV IN (SELECT MAGV FROM GIAOVIEN 
							                  WHERE HOTEN='NGUYEN TO LAN')
				               AND MAMH IN (SELECT MAMH FROM MONHOC 
							                WHERE TENMH='CO SO DU LIEU')
		)
	)
--Bai 9
--C1
SELECT M2.MAMH, M2.TENMH
    FROM
        DIEUKIEN D INNER JOIN MONHOC M on D.MAMH = M.MAMH
        INNER JOIN MONHOC M2 ON D.MAMH_TRUOC = M2.MAMH
    WHERE M.TENMH='CO SO DU LIEU'
--C2
SELECT MAMH, TENMH FROM MONHOC
WHERE MAMH IN (SELECT MAMH_TRUOC FROM DIEUKIEN
			   WHERE MAMH IN (SELECT MAMH FROM MONHOC 
							  WHERE TENMH='CO SO DU LIEU')
				)
--Bai 10
--C1
SELECT M2.MAMH, M2.TENMH
    FROM
        DIEUKIEN D INNER JOIN MONHOC M on D.MAMH_TRUOC = M.MAMH
     INNER JOIN MONHOC M2 ON D.MAMH = M2.MAMH
    WHERE M.TENMH = 'CAU TRUC ROI RAC'
--C2
SELECT MAMH, TENMH FROM MONHOC
WHERE MAMH IN (SELECT MAMH FROM DIEUKIEN
			   WHERE MAMH_TRUOC IN (SELECT MAMH FROM MONHOC 
							        WHERE TENMH='CAU TRUC ROI RAC')
			   )
--BAI11 
SELECT HOTEN FROM GIAOVIEN
WHERE MAGV IN (SELECT MAGV FROM GIANGDAY
			   WHERE HOCKY=1
			   AND NAM=2006
			   AND MAMH='CTRR'
			   AND MALOP='K11'
			   )
INTERSECT
SELECT HOTEN FROM GIAOVIEN
WHERE MAGV IN (SELECT MAGV FROM GIANGDAY
			   WHERE HOCKY=1
			   AND NAM=2006
			   AND MAMH='CTRR'
			   AND MALOP='K12'
			   )
--BAI12  

SELECT MAHV, HO, TEN FROM HOCVIEN
WHERE MAHV IN (SELECT MAHV FROM KETQUATHI
			   WHERE MAMH='CSDL'
			   AND KQUA='Khong Dat'
			   AND LANTHI=1)
EXCEPT
SELECT MAHV, HO, TEN FROM HOCVIEN
WHERE MAHV IN (SELECT MAHV FROM KETQUATHI
			   WHERE MAMH='CSDL'
			   AND LANTHI>1)

--BAI13
SELECT MAGV, HOTEN FROM GIAOVIEN
WHERE MAGV NOT IN (SELECT MAGV FROM GIANGDAY)

--BAI14
SELECT MAGV, HOTEN FROM GIAOVIEN GV
WHERE MAGV NOT IN (SELECT MAGV FROM GIANGDAY
				   WHERE MAMH IN (SELECT MAMH FROM MONHOC
								  WHERE MAKHOA=GV.MAKHOA)			
					)

--BAI15
SELECT HO, TEN FROM HOCVIEN
WHERE MALOP='K11' 
AND MAHV IN (SELECT MAHV FROM KETQUATHI
			 WHERE LANTHI>3 AND KQUA='Khong Dat')
UNION
SELECT HO, TEN FROM HOCVIEN
WHERE MALOP='K11' 
AND MAHV IN (SELECT MAHV FROM KETQUATHI
			 WHERE LANTHI=2 
			 AND MAMH='CTRR'
			 AND DIEM=5)

--BAI16  
SELECT HOTEN FROM GIAOVIEN
    INNER JOIN
	(SELECT MAGV
     FROM GIANGDAY
     WHERE MAMH='CTRR'
     GROUP BY MAGV, HOCKY, NAM
     HAVING COUNT (MALOP) >= 2) AS ANS
ON GIAOVIEN.MAGV = ANS.MAGV

--BAI 17
SELECT HOCVIEN.MAHV, HO + ' ' + TEN AS HOTEN, LANTHI, DIEM FROM
             HOCVIEN
INNER JOIN
(SELECT KQT.MAHV, LANTHI, DIEM FROM
    KETQUATHI KQT
INNER JOIN
(SELECT MAHV, MAX( LANTHI) AS LTC FROM KETQUATHI
WHERE MAMH = 'CSDL'
GROUP BY MAHV) AS LTC
ON LTC.MAHV = KQT.MAHV AND  LTC.LTC = KQT.LANTHI
WHERE KQT.MAMH = 'CSDL') AS KQLTC
ON KQLTC.MAHV = HOCVIEN.MAHV

--BAI18
SELECT HOCVIEN.MAHV, HO + ' ' + TEN AS HOTEN, DIEM FROM
             HOCVIEN
INNER JOIN
(SELECT KQT.MAHV, LANTHI, DIEM FROM
    KETQUATHI KQT
INNER JOIN
(SELECT MAHV, MAX(DIEM) AS DCN FROM KETQUATHI
WHERE MAMH IN (SELECT MAMH FROM MONHOC WHERE TENMH='Co So Du Lieu')
GROUP BY MAHV) AS DCN
ON DCN.MAHV = KQT.MAHV AND  DCN.DCN = KQT.DIEM
WHERE KQT.MAMH IN (SELECT MAMH FROM MONHOC WHERE TENMH='Co So Du Lieu')) AS KQCN
ON KQCN.MAHV = HOCVIEN.MAHV


