USE QuanLyBanHang;
-- BAI 11
CREATE TRIGGER trg_ins_hd ON HOADON
FOR INSERT
AS
BEGIN
	DECLARE @NGAYHD SMALLDATETIME, @MAKH CHAR(4), @NGAYDK SMALLDATETIME

	SELECT @NGAYHD=NGHD, @MAKH=MAKH
	FROM INSERTED
	SELECT @NGAYDK=NGDK
	FROM KHACHHANG
	WHERE MAKH=@MAKH
	IF(@NGAYHD<@NGAYDK)
	BEGIN
		PRINT 'LOI: NGAY HOA DON KHONG HOP LE!'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM MOI MOT HOA DON THANH CONG'
	END
END
--BAI 12
CREATE TRIGGER trg_ins_hdbai12 ON HOADON
FOR INSERT
AS
BEGIN
	DECLARE @NGAYHD SMALLDATETIME, @MANV CHAR(4), @NGAYVL SMALLDATETIME
	SELECT @NGAYHD=NGHD, @MANV=MANV
	FROM INSERTED
	SELECT @NGAYVL=NGVL 
	FROM NHANVIEN
	WHERE @MANV=MANV
	IF(@NGAYHD<@NGAYVL)
	BEGIN
		PRINT 'LOI: NGAY HOA DON KHONG HOP LE!'
		ROLLBACK TRANSACTION
	END
	ELSE
	BEGIN
		PRINT 'THEM MOI MOT HOA DON THANH CONG'
	END
END
--BAI 13
CREATE TRIGGER INSERT_HOADON_CAU13 ON HOADON
    FOR UPDATE
    AS
    BEGIN
        DECLARE @sohd INT
        SELECT  @sohd  = SOHD FROM inserted
        UPDATE HOADON
        SET TRIGIA = 0
        WHERE @sohd = SOHD
    END

CREATE TRIGGER UPDATE_CTHD_CAU13 ON CTHD
    FOR UPDATE
    AS
    BEGIN
        DECLARE @sohd INT, @SLC INT, @SLM INT, @GTC MONEY, @GTM MONEY, @MASP CHAR(4), @GIA MONEY

        SELECT @sohd = SOHD, @SLC = SL, @MASP = MASP FROM deleted
        SELECT @SLM = SL FROM  inserted
        SELECT @GIA = GIA FROM SANPHAM WHERE SANPHAM.MASP = @MASP
        SELECT @GTC = @SLC * @GIA
        SELECT @GTM = @SLM * @GIA
        UPDATE HOADON
        SET TRIGIA = TRIGIA - @GTC + @GTM
        WHERE SOHD = @sohd
    END

CREATE OR ALTER TRIGGER INSERT_CTHD_CAU13 ON CTHD
    FOR
    INSERT
    AS
    BEGIN
        DECLARE @SOHD INT, @SL INT, @GIA MONEY, @MASP CHAR(4), @TONGTRIGIA MONEY
        SELECT @SOHD = SOHD, @SL = SL, @MASP = MASP FROM inserted
        SELECT @GIA = GIA FROM SANPHAM WHERE MASP = @MASP
        SELECT @TONGTRIGIA = @GIA * @SL
        UPDATE HOADON
        SET TRIGIA = TRIGIA + @TONGTRIGIA
        WHERE SOHD = @SOHD
    END

CREATE OR ALTER TRIGGER DELETE_CTHD_CAU13 ON CTHD
    FOR
    DELETE
    AS
    BEGIN
        DECLARE @SOHD INT, @SL INT, @GIA MONEY, @MASP CHAR(4), @TONGTRIGIA MONEY
        SELECT @SOHD = SOHD, @SL = SL, @MASP = MASP FROM deleted
        SELECT @GIA = GIA FROM SANPHAM WHERE MASP = @MASP
        SELECT @TONGTRIGIA = @GIA * @SL
        UPDATE HOADON
        SET TRIGIA = TRIGIA - @TONGTRIGIA
        WHERE SOHD = @SOHD
    END

--Bai 14
CREATE TRIGGER trg_update_doanhso_khachhang ON KHACHHANG
FOR UPDATE
    AS
BEGIN
    DECLARE @doanhso MONEY
    DECLARE @tongtrigia MONEY
    SELECT @doanhso = DOANHSO FROM INSERTED
    SELECT @tongtrigia = SUM(TRIGIA)
    FROM HOADON,
         INSERTED
    WHERE HOADON.MAKH = INSERTED.MAKH

    IF @doanhso <> @tongtrigia
        BEGIN
            ROLLBACK TRAN
        END
END


