USE QuanLyGiaoVu;
-- BAI 9
CREATE TRIGGER trg_validate_classleader ON LOP
FOR INSERT, UPDATE
AS
BEGIN
    DECLARE @trglop CHAR(5)
    DECLARE @malop CHAR(3)
    SELECT @trglop = TRGLOP FROM INSERTED
    SELECT @malop = MALOP FROM INSERTED
    IF @trglop NOT IN (SELECT MAHV FROM HOCVIEN WHERE HOCVIEN.MALOP= @malop)
    BEGIN
        PRINT N'học sinh này không thuộc lớp'
        ROLLBACK TRAN
    END
END;
-- BAI 10
CREATE TRIGGER trg_validate_trgkhoa ON KHOA
FOR INSERT, UPDATE
AS
BEGIN
    DECLARE @trgkhoa CHAR(5)
    DECLARE @makhoa CHAR(3)
    DECLARE @hocvi VARCHAR(10)
    SELECT @trgkhoa = TRGKHOA FROM INSERTED
    SELECT @makhoa = MAKHOA FROM INSERTED
    SELECT @hocvi = HOCVI FROM GIAOVIEN WHERE @trgkhoa = MAGV

    IF @hocvi NOT IN ('TS','PTS')
    BEGIN
        PRINT N'Học vị của trường khoa không phù hợp'
        ROLLBACK TRAN
    END
END;
--BAI 15
CREATE TRIGGER trg_kiem_tra_ngay_thi ON KETQUATHI
FOR UPDATE, INSERT
AS
BEGIN
    DECLARE @mahv CHAR(5)
    DECLARE @malop CHAR(3)
    DECLARE @mamh VARCHAR(10)
    DECLARE @ngaykt DATETIME
    DECLARE @ngaythi DATETIME

    SELECT @mahv = MAHV FROM INSERTED
    SELECT @mamh = MAMH FROM INSERTED
    SELECT @ngaythi =NGTHI FROM INSERTED
    SELECT @malop = MALOP FROM HOCVIEN WHERE @mahv = MAHV
    SELECT @ngaykt = DENNGAY FROM GIANGDAY WHERE @malop = MALOP AND @mamh = MAMH

    IF @ngaykt >= @ngaythi
    BEGIN
        ROLLBACK TRAN
    END
END
--BAI 16
CREATE TRIGGER trg_test_b16 ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MALOP CHAR(3)
	DECLARE @HOCKY TINYINT
	DECLARE @NAM SMALLINT
	DECLARE @SL TINYINT

	SELECT @MALOP=MALOP FROM inserted
	SELECT @HOCKY=HOCKY FROM inserted
	SELECT @NAM=NAM FROM inserted
	SELECT @SL=COUNT(MAMH) FROM GIANGDAY
	WHERE @MALOP=MALOP
	AND @HOCKY=HOCKY
	AND @NAM=NAM
	IF(@SL>3)
	BEGIN
		ROLLBACK TRAN
	END
	ELSE
	BEGIN
		PRINT 'THEM THANH CONG'
	END
END
-- BAI 17
CREATE TRIGGER INSERT_LOP_CAU17 ON LOP
FOR INSERT
AS
BEGIN
    DECLARE @MALOP CHAR(3)
    SELECT @MALOP = MALOP FROM inserted
    UPDATE LOP
    SET SISO = 0
    WHERE MALOP = @MALOP
END

CREATE OR ALTER TRIGGER INSERT_HOCVIEN_CAU17 ON HOCVIEN
FOR INSERT
    AS
BEGIN
    DECLARE @MALOP CHAR(3)
    SELECT @MALOP = MALOP FROM INSERTED
    UPDATE LOP
    SET SISO = SISO + 1
    WHERE MALOP = @MALOP
END

CREATE OR ALTER TRIGGER UPDATE_HOCVIEN_CAU17 ON HOCVIEN
FOR UPDATE
AS
BEGIN
    DECLARE @MLM CHAR(3), @MLC CHAR(3)
    SELECT @MLM = MALOP FROM INSERTED
    SELECT @MLC = MALOP FROM DELETED
    UPDATE LOP SET SISO = SISO + 1 WHERE MALOP = @MLM
    UPDATE LOP SET SISO = SISO - 1 WHERE MALOP = @MLC
END

CREATE OR ALTER TRIGGER DELETE_HOCVIEN_CAU17 ON HOCVIEN
FOR DELETE
AS
BEGIN
    DECLARE @MALOP CHAR(3)
    SELECT @MALOP = MALOP FROM DELETED
    UPDATE LOP
    SET SISO = SISO - 1
    WHERE MALOP = @MALOP
END
--BAI 18
CREATE OR ALTER TRIGGER DIEUKIEN_CAU18 ON DIEUKIEN
FOR INSERT ,UPDATE
AS
BEGIN
    DECLARE @MAMH VARCHAR(10), @MAMH_TRUOC VARCHAR(10)
    SELECT @MAMH = MAMH, @MAMH_TRUOC = MAMH_TRUOC FROM INSERTED
    IF (@MAMH = @MAMH_TRUOC)
    BEGIN
        ROLLBACK TRAN
        PRINT 'MAMH VA MAMHTRUOC KHONG DUOC GIONG NHAU'
    END
    ELSE
    BEGIN
        IF (EXISTS(SELECT * FROM DIEUKIEN WHERE MAMH = @MAMH_TRUOC AND MAMH_TRUOC = @MAMH))
        BEGIN
            ROLLBACK TRAN
            PRINT 'DIEU KIEN KHONG THOA MAN'
        END
    END
END
--BAI 19
CREATE TRIGGER trg_B19 ON GIAOVIEN
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAGV CHAR(4)
	DECLARE @HOCVI VARCHAR(10)
	DECLARE @HOCHAM VARCHAR(10)
	DECLARE @HESO NUMERIC(4,2)
	DECLARE @MUCLUONG MONEY

	SELECT @MUCLUONG=MUCLUONG FROM inserted
	SELECT @MAGV=MAGV FROM inserted
	SELECT @HOCVI=HOCVI FROM inserted
	SELECT @HOCHAM=HOCHAM FROM inserted
	SELECT @HESO=HESO FROM inserted
	SELECT MAGV=@MAGV FROM GIAOVIEN 
	WHERE HOCVI=@HOCVI
	AND @HOCHAM=HOCHAM
	AND @HESO=HESO
	IF(@MUCLUONG <> (SELECT MUCLUONG FROM GIAOVIEN WHERE MAGV<>@MAGV AND HOCVI=@HOCVI AND HOCHAM=@HOCHAM AND HESO=@HESO))
	BEGIN
		ROLLBACK TRAN
	END
END
--BAI 20
CREATE TRIGGER trg_B20 ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
    DECLARE @LANTHI TINYINT, @MAHV CHAR(5), @MAMH VARCHAR(10),@DIEMTHILANTRUOC NUMERIC(4,2)
    SELECT @MAHV = MAHV , @MAMH = MAMH, @LANTHI = LANTHI FROM inserted
    IF(@LANTHI > 1)
    BEGIN
        SELECT @DIEMTHILANTRUOC = DIEM
        FROM KETQUATHI
        WHERE MAHV = @MAHV
        AND MAMH = @MAMH
        AND LANTHI = @LANTHI - 1
        IF(@DIEMTHILANTRUOC > 5)
        BEGIN
            PRINT 'KHONG DUOC THI LAI'
            ROLLBACK TRANSACTION
        END
    END
END
--BAI 21
CREATE TRIGGER trg_B21 ON KETQUATHI
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAHV CHAR(5)
	DECLARE @MAMH VARCHAR(10)
	DECLARE @LANTHI TINYINT
	DECLARE @NGTHISAU SMALLDATETIME
	DECLARE @NGTHITRUOC SMALLDATETIME

	SELECT @MAHV=MAHV FROM inserted
	SELECT @MAMH=MAMH FROM inserted
	SELECT @LANTHI=LANTHI FROM inserted
	SELECT @NGTHISAU=NGTHI FROM inserted
	IF(@LANTHI>1)
	BEGIN
		SELECT @NGTHITRUOC=NGTHI
		FROM KETQUATHI
		WHERE MAHV=@MAHV
		AND MAMH=@MAMH
		AND LANTHI=@LANTHI-1
		IF(@NGTHISAU<=@NGTHITRUOC)
		BEGIN
			ROLLBACK TRAN
		END
	END
END
--BAI 22
CREATE OR ALTER TRIGGER GIANGDAY_CAU23 ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
    DECLARE @MALOP CHAR(3), @MAMH VARCHAR(10), @MAMH_TRUOC VARCHAR(10)
    SELECT @MALOP = MALOP, @MAMH = MAMH FROM INSERTED
    SELECT @MAMH_TRUOC = MAMH_TRUOC FROM DIEUKIEN WHERE MAMH = @MAMH
    IF NOT EXISTS (SELECT 1 FROM GIANGDAY WHERE MAMH = @MAMH_TRUOC
                                        AND MALOP = @MALOP)
    BEGIN
        PRINT 'MON HOC TRUOC CHUA DUOC HOC'
        ROLLBACK TRANSACTION
    END
END
--BAI 23
CREATE TRIGGER trg_B23 ON GIANGDAY
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @MAGV CHAR(4)
	DECLARE @MAMH VARCHAR(10)
	DECLARE @MAKHOAMH VARCHAR(4)
	DECLARE @MAKHOAGV VARCHAR(4)
	
	SELECT @MAGV=MAGV FROM inserted
	SELECT @MAMH=MAMH FROM inserted
	SELECT @MAKHOAMH=MAKHOA FROM MONHOC WHERE @MAMH=MAMH
	SELECT @MAKHOAGV=MAKHOA FROM GIAOVIEN WHERE @MAGV=MAGV
	IF(@MAKHOAMH<>@MAKHOAGV)
	BEGIN
		ROLLBACK TRAN
	END
END