CREATE DATABASE BAITHI;
USE BAITHI;
CREATE TABLE NHACUNGCAP (
	MANCC CHAR(10),
	TENNCC VARCHAR(40),
	QUOCGIA VARCHAR(40),
	LOAINCC VARCHAR(40)
	CONSTRAINT PK_NCC PRIMARY KEY (MANCC)
	)

CREATE TABLE DUOCPHAM (
	MADP CHAR(10),
	TENDP VARCHAR(40),
	LOAIDP VARCHAR(40),
	GIA MONEY
	CONSTRAINT PK_DP PRIMARY KEY (MADP)
	)

CREATE TABLE PHIEUNHAP (
	SOPN CHAR(10),
	NGNHAP DATE,
	MANCC CHAR(10),
	LOAINHAP VARCHAR(40)
	CONSTRAINT PK_PN PRIMARY KEY(SOPN)
	)
 CREATE TABLE CTPN (
	SOPN CHAR(10),
	MADP CHAR(10),
	SOLUONG INT
	CONSTRAINT PK_CTPN PRIMARY KEY(SOPN,MADP)
	)
 ALTER TABLE PHIEUNHAP ADD
 CONSTRAINT FK_PN_NCC FOREIGN KEY (MANCC) REFERENCES NHACUNGCAP(MANCC)
 ALTER TABLE CTPN ADD
 CONSTRAINT FK_CTPN_DP FOREIGN KEY (MADP) REFERENCES DUOCPHAM(MADP),
 CONSTRAINT FK_CTPN_PN FOREIGN KEY (SOPN) REFERENCES PHIEUNHAP(SOPN)

 -- Bảng NHACUNGCAP
INSERT INTO NHACUNGCAP (MANCC, TENNCC, QUOCGIA, LOAINCC)
VALUES
('NCC01', 'Phuc Hung', 'Viet Nam', 'Thuong xuyen'),
('NCC02', 'J. B. Pharmaceuticals', 'India', 'Vang lai'),
('NCC03', 'Sapharco', 'Singapore', 'Vang lai');

-- Bảng DUOCPHAM
INSERT INTO DUOCPHAM (MADP, TENDP, LOAIDP, GIA)
VALUES
('DP01', 'Thuoc ho PH', 'Siro', 120000),
('DP02', 'Zecuf Herbal CouchRemedy', 'Vien nen', 200000),
('DP03', 'Cotrim', 'Vien sui', 80000);

-- Bảng PHIEUNHAP
INSERT INTO PHIEUNHAP (SOPN, NGNHAP, MANCC, LOAINHAP)
VALUES
('00001', '2017-11-22', 'NCC01', 'Noi dia'),
('00002', '2017-12-04', 'NCC03', 'Nhap khau'),
('00003', '2017-12-10', 'NCC02', 'Nhap khau');

-- Bảng CTPN
INSERT INTO CTPN (SOPN, MADP, SOLUONG)
VALUES
('00001', 'DP01', 100),
('00001', 'DP02', 200),
('00003', 'DP03', 543);
--CAU 3
ALTER TABLE DUOCPHAM
ADD CONSTRAINT CHK_GIASIRO CHECK (NOT (LOAIDP = 'Siro') OR GIA > 100000)
--CAU4
CREATE TRIGGER TRG_C4 ON PHIEUNHAP
FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @LOAINHAP VARCHAR(40)
	
	SELECT @LOAINHAP=LOAINHAP FROM inserted WHERE MANCC IN(SELECT MANCC FROM NHACUNGCAP WHERE QUOCGIA<>'Viet Nam')
	IF(@LOAINHAP<>'Nhap khau')
	BEGIN
		PRINT'QUOCGIA KHAC VN THI PHAI NHAP KHAU'
		ROLLBACK TRAN
	END
END 

--CAU5
SELECT * FROM PHIEUNHAP
WHERE YEAR(NGNHAP)=2017 AND MONTH(NGNHAP)=12
ORDER BY NGNHAP ASC



--CAU6
SELECT TOP 1 CTPN.MADP, DUOCPHAM.TENDP, SUM(CTPN.SOLUONG) AS TONG_SOLUONG
FROM PHIEUNHAP
JOIN CTPN ON PHIEUNHAP.SOPN = CTPN.SOPN
JOIN DUOCPHAM ON CTPN.MADP = DUOCPHAM.MADP
WHERE YEAR(PHIEUNHAP.NGNHAP) = 2017
GROUP BY CTPN.MADP, DUOCPHAM.TENDP
order by SUM(CTPN.SOLUONG) DESC


--CAU7
SELECT DISTINCT DP.MADP, DP.TENDP
FROM DUOCPHAM DP
JOIN CTPN ON CTPN.MADP = DP.MADP
JOIN PHIEUNHAP  PN ON CTPN.SOPN = PN.SOPN
JOIN NHACUNGCAP  NCC ON PN.MANCC = NCC.MANCC
WHERE NCC.LOAINCC = 'Thuong xuyen'
  AND DP.MADP NOT IN (
      SELECT CTPN.MADP
      FROM PHIEUNHAP
      JOIN CTPN ON PHIEUNHAP.SOPN = CTPN.SOPN
      JOIN NHACUNGCAP ON PHIEUNHAP.MANCC = NHACUNGCAP.MANCC
      WHERE NHACUNGCAP.LOAINCC = 'Vang lai'
  );
--CAU8
SELECT DISTINCT NCC.MANCC, NCC.TENNCC
FROM DUOCPHAM DP
JOIN CTPN ON CTPN.MADP = DP.MADP
JOIN PHIEUNHAP  PN ON CTPN.SOPN = PN.SOPN
JOIN NHACUNGCAP  NCC ON PN.MANCC = NCC.MANCC
WHERE DP.GIA>100000
AND YEAR(PN.NGNHAP)=2017
GROUP BY NCC.MANCC,NCC.TENNCC
HAVING COUNT(DP.MADP)= (
SELECT COUNT(DP.MADP) FROM DUOCPHAM DP
JOIN CTPN ON CTPN.MADP = DP.MADP
JOIN PHIEUNHAP  PN ON CTPN.SOPN = PN.SOPN
JOIN NHACUNGCAP  NCC ON PN.MANCC = NCC.MANCC
WHERE GIA>100000
AND YEAR(NGNHAP)='2017'
)

